# Generated by Django 3.0.2 on 2020-04-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified',
        ),
    ]
